using System;
using Newtonsoft.Json;

namespace Nop.Plugin.Payments.QualpayCheckout.Domain
{
    /// <summary>
    /// Represents a single transaction made through Qualpay Checkout.
    /// </summary>
    public class Transaction
    {
        /// <summary>
        /// Gets or sets a unique identifier generated when a checkout resource is created. 
        /// </summary>
        [JsonProperty(PropertyName = "checkout_id")]
        public string CheckoutId { get; set; }

        /// <summary>
        /// Gets or sets a unique identifier generated by the payment gateway for each transaction. 
        /// </summary>
        [JsonProperty(PropertyName = "pg_id")]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or sets the response code from the Qualpay payment gateway
        /// </summary>
        [JsonProperty(PropertyName = "rcode")]
        public string ResponseCode { get; set; }

        /// <summary>
        /// Gets or sets a text description of the authorization response code from Qualpay payment gateway 
        /// </summary>
        [JsonProperty(PropertyName = "rmsg")]
        public string ResponseMessage { get; set; }

        /// <summary>
        /// Gets or sets a status of transaction
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets the date timestamp when the transaction was submitted.
        /// </summary>
        [JsonProperty(PropertyName = "tran_time")]
        public DateTime TransactionTime { get; set; }

        /// <summary>
        /// Gets or sets a masked card number.
        /// </summary>
        [JsonProperty(PropertyName = "card_number")]
        public string CardNumber { get; set; }

        /// <summary>
        /// Gets or sets the transaction amount of this transaction.
        /// </summary>
        [JsonProperty(PropertyName = "amt_tran")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or sets the ISO numeric currency code for the transaction. 
        /// </summary>
        [JsonProperty(PropertyName = "tran_currency")]
        public int CurrencyIsoCode { get; set; }

        /// <summary>
        /// Gets or sets the currency code of the transaction. 
        /// </summary>
        [JsonProperty(PropertyName = "currencyAlpha")]
        public string CurrencyAlpha { get; set; }

        /// <summary>
        /// Gets or sets a purchase identifier (or invoice number) for the transaction. 
        /// </summary>
        [JsonProperty(PropertyName = "purchase_id")]
        public string PurchaseId { get; set; }

        /// <summary>
        /// Gets or sets the unique profile ID used to submit the transaction. 
        /// </summary>
        [JsonProperty(PropertyName = "profile_id")]
        public string ProfileId { get; set; }

        /// <summary>
        /// Gets or sets the authorization code returned when the transaction was sent to the card issuer for approval.
        /// </summary>
        [JsonProperty(PropertyName = "auth_code")]
        public string AuthorizationCode { get; set; }

        /// <summary>
        /// Gets or sets the result from the card issuer.
        /// </summary>
        [JsonProperty(PropertyName = "cvv2_result")]
        public string Cvv2Result { get; set; }

        /// <summary>
        /// Gets or sets the result from the card issuer.
        /// </summary>
        [JsonProperty(PropertyName = "avs_result")]
        public string AvsResult { get; set; }

        /// <summary>
        /// Gets or sets the Qualpay Account Identifier.
        /// </summary>
        [JsonProperty(PropertyName = "merchant_id")]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or sets the IP address of the device initiating the payment.
        /// </summary>
        [JsonProperty(PropertyName = "client_ip")]
        public string CustomerIpAddress { get; set; }

        /// <summary>
        /// Gets or sets the DBA name associated with the profile.
        /// </summary>
        [JsonProperty(PropertyName = "dba_name")]
        public string DbaName { get; set; }

        /// <summary>
        /// Gets or sets the customer information submitted with the transaction.
        /// </summary>
        [JsonProperty(PropertyName = "customer")]
        public Customer Customer { get; set; }
    }
}